name: astrologics
channels:
  - conda-forge
  - colomoto
dependencies:
  - python
  - astrologics
  - pandas
  - h5py
  - numpy<=2.2
  - scipy
  - scikit-learn
  - tslearn
  - fastcluster
  - seaborn
  - jupyterlab
  - ipylab
  - pymaboss
  - boolsim-python 
  - mpbn
  - pip
  - pip:
    - netrd
