{% set name = "astrologics" %}
{% set version = "0.3.3" %}
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ..

build:
  noarch: python

requirements:
  build:
    - python >=3.10
    - setuptools

  run:
    - python >=3.10
    - pandas
    - h5py
    - scipy
    - scikit-learn
    - tslearn
    - fastcluster
    - seaborn
    - jupyterlab
    - ipylab
    - pymaboss
    - boolsim-python 
    - mpbn
    - tqdm
    - pip

test:
  imports:
    - astrologics
  
  
about:
  home: https://github.com/sysbio-curie/AstroLogics
  summary: 'A simulation-based framework for the analysis of Boolean model ensembles.'

